server:
  port: 8085
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bkp3/microservice-config-HRS
          clone-on-start: true